version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - app
  web:
    build: .
    command: mix phx.server
    volumes:
      - ./bodekasse:/code
    ports:
      - 4000:4000
    depends_on:
      - db
    networks:
      - app
networks:
  app:
